version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6000:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=YYYYYYY
      - POSTGRES_DB=VSDB0